default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: postgres
  password: postgres

development:
  <<: *default
  database: customer_loan_database_development

test:
  <<: *default
  database: customer_loan_database_test

production:
  <<: *default
  database: customer_loan_database_production